# Generated by Django 3.2.9 on 2021-12-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funquizgame', '0002_accesscode'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='title',
            field=models.CharField(default='', max_length=60, verbose_name='Game Title'),
            preserve_default=False,
        ),
    ]
