# Generated by Django 3.2.9 on 2021-12-22 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funquizgame', '0003_game_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='realanswer',
            name='answer_created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Creation time'),
        ),
    ]
