# Generated by Django 3.2.9 on 2021-12-24 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funquizgame', '0004_realanswer_answer_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiondata',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
