# Generated by Django 4.1.3 on 2022-12-10 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funquizgame", "0008_game_current_survey_alter_game_status"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AccessCode",
            new_name="GameUserParticipation",
        ),
        migrations.AlterField(
            model_name="gameuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("ht", "Host"),
                    ("vw", "Viewer"),
                    ("pt", "Participant"),
                    ("vp", "Viewer participant"),
                ],
                default="vw",
                max_length=3,
                verbose_name="User role",
            ),
        ),
    ]
