# Generated by Django 4.1.3 on 2024-12-23 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("funquizgame", "0011_team_captain"),
    ]

    operations = [
        migrations.CreateModel(
            name="BetOpportunity",
            fields=[
                (
                    "realdataabstract_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="funquizgame.realdataabstract",
                    ),
                ),
                (
                    "is_shown",
                    models.BooleanField(
                        default=False, verbose_name="Opportunity is shown?"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="funquizgame.realquestion",
                    ),
                ),
            ],
            bases=("funquizgame.realdataabstract",),
        ),
        migrations.AddField(
            model_name="game",
            name="current_bet",
            field=models.UUIDField(blank=True, null=True, verbose_name="Current bet"),
        ),
        migrations.AlterField(
            model_name="game",
            name="status",
            field=models.TextField(
                choices=[
                    ("beg", "Beginning"),
                    ("st", "Setting teams"),
                    ("ct", "Choosing teams"),
                    ("dash", "Dashboard"),
                    ("bet", "Betting"),
                    ("ques", "Question"),
                    ("surv", "Survey"),
                    ("end", "Ending"),
                ],
                default="beg",
                verbose_name="Current game status",
            ),
        ),
        migrations.AlterField(
            model_name="questiondata",
            name="question_type",
            field=models.SmallIntegerField(
                choices=[
                    (1, "Enter a number"),
                    (2, "First button click"),
                    (3, "Family feud type"),
                    (4, "Open ended question"),
                ],
                verbose_name="Question type*",
            ),
        ),
        migrations.CreateModel(
            name="BetPlacedValue",
            fields=[
                (
                    "realdataabstract_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="funquizgame.realdataabstract",
                    ),
                ),
                (
                    "size",
                    models.IntegerField(blank=True, null=True, verbose_name="Bet size"),
                ),
                (
                    "is_shown",
                    models.BooleanField(default=False, verbose_name="Answer is shown?"),
                ),
                ("assigned", models.IntegerField(default=0, verbose_name="Assigned?")),
                (
                    "bet_created",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Creation time"
                    ),
                ),
                (
                    "bet",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="funquizgame.betopportunity",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="funquizgame.team",
                    ),
                ),
            ],
            bases=("funquizgame.realdataabstract",),
        ),
    ]
