# Generated by Django 4.1.3 on 2024-12-25 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "funquizgame",
            "0012_betopportunity_game_current_bet_alter_game_status_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="betplacedvalue",
            old_name="size",
            new_name="betsize",
        ),
    ]
