# Generated by Django 4.1.3 on 2024-12-27 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funquizgame", "0013_rename_size_betplacedvalue_betsize"),
    ]

    operations = [
        migrations.AddField(
            model_name="realanswer",
            name="text_answer",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Entered text value"
            ),
        ),
    ]
